### ISSUE TITLE
App crash trying to connect to hue Bridge

### ISSUE THREAD

**Issue by gajdur** [athombv/com.google.chromecast#12]
App is always crashing trying to connect to the Hue Bridge.

**Comment by gajdur** [comment]
Still having this issue:
App is crashing with this Log:
Stack trace:

Error: connect ETIMEDOUT 192.168.10.3:80
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

Exit code: 1

-------------
192.168.10.3 is my Hue Bridge.

**Comment by matjaz** [comment]
Can't really debug this since I don't have hue Bridge.

Chromecast is using mdns
see https://github.com/matjaz/com.google.chromecast/blob/master/node_modules/chromecast-api/lib/Browser.js#L37
So first step is to see which devices are discovered on your LAN with mdns.
You can do this using shell `dns-sd -B _chromecast .`
Or changing chromecast app and echo discovered devices in driver.

**Comment by BasKiers** [comment]
The app has been rewritten and the hue bridge has been filtered from the device list. Please open a new issue if you experience problems.
