### ISSUE TITLE
[Feature-Request] Multiroom / Output Homeys Voice

### ISSUE THREAD

**Issue by peaoo** [athombv/com.google.chromecast#20]
If it is not already planned (maybe with the media-update): Please support Multiroom-Chomecast Audio. For media and if it is possible for Homeys voice output aswell.

**Comment by BasKiers** [comment]
Multiroom is supported as of v2.1.0! 

I will close this issue since Homey voice output will not be something that will be implemented by this app. In the future this app will expose the chromecast audio as a speaker and it is up to Homey Client to decide if Homey's voice will be available over external speakers which I don't think is the plan.
