### ISSUE TITLE
App crashing, even if it isn't configured

### ISSUE THREAD

**Issue by Keverjeroen** [athombv/com.google.chromecast#9]
The Chromecast app is crashing after a while (exclamation mark in red triangle). Even after removing and reinstalling, and not configuring anything in the app, it crashes after a while..

Homey: 0.8.38, Chromecast: 0.11.1

**Comment by matjaz** [comment]
can you provide crash log? (hover over exclamation mark)

**Comment by Keverjeroen** [comment]
Here it is:

> Stack trace:
> 
> Error: read ECONNRESET
> at exports._errnoException (util.js:870:11)
> at TCP.onread (net.js:552:26),Error: socket hang up
> at createHangUpError (_http_client.js:200:15)
> at Socket.socketCloseListener (_http_client.js:232:23)
> at emitOne (events.js:82:20)
> at Socket.emit (events.js:169:7)
> at TCP._onclose (net.js:477:12)

**Comment by Keverjeroen** [comment]
Maybe this helps too. It looks like that RAM-usage is going up. This is while the app is still unconfigured and not in use:

![chromecast_ram](https://cloud.githubusercontent.com/assets/18548628/16038625/20ac3888-3226-11e6-8a09-e4bd92c29acd.png)

**Comment by Radiotechniman** [comment]
I have a similar one, though the device is configured, but its turned off at the moment 
(which is the reason why it's not reachable, though it should not crash because of that.. ) 

Stack trace:

Error: connect ENETUNREACH 192.168.1.228:8008 - Local (0.0.0.0:0)
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at connect (net.js:865:16)
at net.js:953:9
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)

Exit code: 1

**Comment by BasKiers** [comment]
The app has been rewritten and all crashes should be fixed. Please open a new issue if you experience problems.
